name: IaC Checks

on:
  pull_request:
    paths: ["**/.tf"]

jobs:
  iac-checks:
    name: IaC Checks
    uses: ehassett/workflows/.github/workflows/iac-checks.yaml@main
    with:
      tool: "tofu"
      tool-version: "1.9.0"
      working-directory: "infrastructure"
